name: dw-refactor-py37
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - pip
  - pytest=7
  - pyyaml=6
  - requests
  - pymysql
  - typing_extensions
  - pip:
      - git+https://github.com/HYDCP/hy-sqlglot.git@77fe22e66498ea4ad996d9c5a172c69d7ac693c8
      - ruff==0.12.0
