"""Explicit pytest test-type taxonomy.

The taxonomy is file-level on purpose: most legacy files group related
scenarios, and pytest adds the type marker to every collected item from the
file through tests/conftest.py.
"""

TEST_TYPE_MARKERS = frozenset(
    {
        "unit",
        "scenario",
        "guard",
        "contract",
    }
)

TEST_TYPE_DESCRIPTIONS = {
    "unit": "Focused tests for pure functions or narrow module behavior.",
    "scenario": "Workflow tests shaped around user-visible behavior.",
    "guard": "Project-level rules that catch unsafe environmental drift.",
    "contract": "Stable output schema, serialization, and payload contracts.",
}

TEST_TYPE_BY_FILE = {
    "tests/assess/test_assess_middle_layer.py": "scenario",
    "tests/assess/test_business_semantics_catalog.py": "scenario",
    "tests/assess/test_code_quality.py": "unit",
    "tests/assess/test_context_builder.py": "unit",
    "tests/assess/test_inspection_contract.py": "unit",
    "tests/assess/test_layer_resolution.py": "unit",
    "tests/assess/test_metadata_flow.py": "unit",
    "tests/assess/test_model_design.py": "unit",
    "tests/assess/test_model_metadata_writer_catalog.py": "scenario",
    "tests/assess/test_model_metadata_writer_generation.py": "scenario",
    "tests/assess/test_model_metadata_writer_updates.py": "scenario",
    "tests/assess/test_report.py": "contract",
    "tests/assess/test_result_model.py": "contract",
    "tests/assess/test_rule_framework.py": "unit",
    "tests/assess/test_scoped_assessment_plan.py": "unit",
    "tests/assess/test_scoring_context_interface.py": "unit",
    "tests/assess/test_shop_model_design_scenarios.py": "scenario",
    "tests/assess/test_table_inspector.py": "unit",
    "tests/benchmarks/test_generate_llm_benchmark.py": "guard",
    "tests/benchmarks/test_lineage_extractor_benchmark_dataset.py": "guard",
    "tests/ddl_deriver/test_ddl_deriver.py": "unit",
    "tests/ddl_deriver/test_git_mode.py": "scenario",
    "tests/ddl_deriver/test_schema_ids.py": "unit",
    "tests/lineage/test_asset_graph.py": "unit",
    "tests/lineage/test_build_schema.py": "unit",
    "tests/lineage/test_cross_job_process_scenarios.py": "scenario",
    "tests/lineage/test_extract_lineage.py": "unit",
    "tests/lineage/test_extract_lineage_edge_cases.py": "unit",
    "tests/lineage/test_extract_lineage_integration.py": "unit",
    "tests/lineage/test_extract_lineage_select_star.py": "unit",
    "tests/lineage/test_import_lineage.py": "scenario",
    "tests/lineage/test_job_dag.py": "unit",
    "tests/lineage/test_job_lineage.py": "unit",
    "tests/lineage/test_layer_function.py": "unit",
    "tests/lineage/test_lineage_cli.py": "scenario",
    "tests/lineage/test_lineage_contract.py": "contract",
    "tests/lineage/test_lineage_ddl.py": "guard",
    "tests/lineage/test_lineage_extraction_performance.py": "guard",
    "tests/lineage/test_lineage_extractor_cache_cli.py": "scenario",
    "tests/lineage/test_lineage_extractor_summary.py": "contract",
    "tests/lineage/test_lineage_formatters.py": "contract",
    "tests/lineage/test_lineage_output_metadata.py": "contract",
    "tests/lineage/test_lineage_query.py": "contract",
    "tests/lineage/test_lineage_view.py": "unit",
    "tests/lineage/test_missing_ddl_warnings.py": "scenario",
    "tests/lineage/test_project_lineage_defaults.py": "guard",
    "tests/lineage/test_refresh_lineage_html.py": "scenario",
    "tests/lineage/test_sql_task_facts.py": "unit",
    "tests/lineage/test_task_cache.py": "unit",
    "tests/lineage/test_trace_lineage.py": "unit",
    "tests/lineage/test_update_to_select.py": "unit",
    "tests/refact/test_artifact_contract.py": "contract",
    "tests/refact/test_change_analysis.py": "unit",
    "tests/refact/test_compare.py": "scenario",
    "tests/refact/test_incremental_lineage.py": "scenario",
    "tests/refact/test_issue_diff.py": "unit",
    "tests/refact/test_plan_artifact.py": "contract",
    "tests/refact/test_qa_pool.py": "unit",
    "tests/refact/test_run_cli.py": "scenario",
    "tests/refact/test_semantic_mode.py": "unit",
    "tests/refact/test_session.py": "contract",
    "tests/refact/test_shadow_executor.py": "unit",
    "tests/refact/test_shadow_manifest.py": "unit",
    "tests/refact/test_shadow_partitions.py": "unit",
    "tests/refact/test_shadow_rewrite.py": "unit",
    "tests/refact/test_shadow_run.py": "scenario",
    "tests/refact/test_shadow_scope.py": "unit",
    "tests/refact/test_verification_plan.py": "contract",
    "tests/refact/test_workspace_snapshot.py": "unit",
    "tests/sql/test_task_template_contract.py": "contract",
    "tests/sql/test_task_template_renderer.py": "unit",
    "tests/test_check_duplicates.py": "unit",
    "tests/test_doris_ddl_validity.py": "guard",
    "tests/test_execution_planner.py": "unit",
    "tests/test_execution_run_lock.py": "unit",
    "tests/test_makefile_python_resolution.py": "guard",
    "tests/test_naming_config.py": "unit",
    "tests/test_process_table_assets.py": "guard",
    "tests/test_project_asset_paths.py": "contract",
    "tests/test_python37_compat.py": "guard",
    "tests/test_python_env_doctor.py": "guard",
    "tests/test_reinit_project.py": "scenario",
    "tests/test_schedule_dag.py": "unit",
    "tests/test_retail_banking_assets.py": "guard",
    "tests/test_retail_banking_dws_ads_specs.py": "contract",
    "tests/test_retail_banking_schema_compiler.py": "unit",
    "tests/test_retail_banking_semantic_specs.py": "contract",
    "tests/test_shop_static_partitions.py": "guard",
    "tests/test_task_asset_discovery.py": "contract",
    "tests/test_task_run.py": "scenario",
    "tests/test_taxonomy.py": "guard",
    "tests/test_text_encoding_config.py": "guard",
}
