-- Human-reviewed semantic target: retail_banking_dm.dim_wc_loan_product
TRUNCATE TABLE retail_banking_dm.dim_wc_loan_product;

INSERT INTO retail_banking_dm.dim_wc_loan_product (
    `id`,
    `name`,
    `short_name`,
    `external_id`,
    `fund_id`,
    `start_date`,
    `close_date`,
    `description`,
    `currency_code`,
    `currency_digits`,
    `currency_multiplesof`,
    `amortization_type`,
    `delinquency_bucket_classification_id`,
    `npv_day_count`,
    `min_principal_amount`,
    `principal_amount`,
    `max_principal_amount`,
    `min_period_payment_rate`,
    `period_payment_rate`,
    `max_period_payment_rate`,
    `discount`,
    `repayment_every`,
    `repayment_frequency_enum`,
    `delinquency_grace_days`,
    `delinquency_start_type`,
    `breach_id`,
    `accounting_type`,
    `near_breach_id`,
    `breach_grace_days`,
    `etl_time`
)
SELECT
    src.`id`,
    src.`name`,
    src.`short_name`,
    src.`external_id`,
    src.`fund_id`,
    src.`start_date`,
    src.`close_date`,
    src.`description`,
    src.`currency_code`,
    src.`currency_digits`,
    src.`currency_multiplesof`,
    src.`amortization_type`,
    src.`delinquency_bucket_classification_id`,
    src.`npv_day_count`,
    src.`min_principal_amount`,
    src.`principal_amount`,
    src.`max_principal_amount`,
    src.`min_period_payment_rate`,
    src.`period_payment_rate`,
    src.`max_period_payment_rate`,
    src.`discount`,
    src.`repayment_every`,
    src.`repayment_frequency_enum`,
    src.`delinquency_grace_days`,
    src.`delinquency_start_type`,
    src.`breach_id`,
    src.`accounting_type`,
    src.`near_breach_id`,
    src.`breach_grace_days`,
    CURRENT_TIMESTAMP AS `etl_time`
FROM retail_banking_dm.ods_fineract_m_wc_loan_product AS src;
