SET @etl_date = COALESCE(@etl_date, CURDATE());

-- Human-reviewed semantic target: retail_banking_dm.dim_share_product
TRUNCATE TABLE retail_banking_dm.dim_share_product;

INSERT INTO retail_banking_dm.dim_share_product (
    `id`,
    `name`,
    `short_name`,
    `external_id`,
    `description`,
    `start_date`,
    `end_date`,
    `currency_code`,
    `currency_digits`,
    `currency_multiplesof`,
    `total_shares`,
    `issued_shares`,
    `totalsubscribed_shares`,
    `unit_price`,
    `capital_amount`,
    `minimum_client_shares`,
    `nominal_client_shares`,
    `maximum_client_shares`,
    `minimum_active_period_frequency`,
    `minimum_active_period_frequency_enum`,
    `lockin_period_frequency`,
    `lockin_period_frequency_enum`,
    `allow_dividends_inactive_clients`,
    `createdby_id`,
    `created_date`,
    `lastmodifiedby_id`,
    `lastmodified_date`,
    `accounting_type`,
    `etl_time`
)
SELECT
    src.`id`,
    src.`name`,
    src.`short_name`,
    src.`external_id`,
    src.`description`,
    src.`start_date`,
    src.`end_date`,
    src.`currency_code`,
    src.`currency_digits`,
    src.`currency_multiplesof`,
    src.`total_shares`,
    src.`issued_shares`,
    src.`totalsubscribed_shares`,
    src.`unit_price`,
    src.`capital_amount`,
    src.`minimum_client_shares`,
    src.`nominal_client_shares`,
    src.`maximum_client_shares`,
    src.`minimum_active_period_frequency`,
    src.`minimum_active_period_frequency_enum`,
    src.`lockin_period_frequency`,
    src.`lockin_period_frequency_enum`,
    src.`allow_dividends_inactive_clients`,
    src.`createdby_id`,
    src.`created_date`,
    src.`lastmodifiedby_id`,
    src.`lastmodified_date`,
    src.`accounting_type`,
    CURRENT_TIMESTAMP AS `etl_time`
FROM retail_banking_dm.ods_fineract_m_share_product AS src;
