-- Human-reviewed semantic target: retail_banking_dm.dim_customer
TRUNCATE TABLE retail_banking_dm.dim_customer;

INSERT INTO retail_banking_dm.dim_customer (
    `id`,
    `account_no`,
    `external_id`,
    `status_enum`,
    `sub_status`,
    `activation_date`,
    `office_joining_date`,
    `office_id`,
    `transfer_to_office_id`,
    `staff_id`,
    `firstname`,
    `middlename`,
    `lastname`,
    `fullname`,
    `display_name`,
    `mobile_no`,
    `is_staff`,
    `gender_cv_id`,
    `date_of_birth`,
    `image_id`,
    `closure_reason_cv_id`,
    `closedon_date`,
    `updated_by`,
    `updated_on`,
    `submittedon_date`,
    `activatedon_userid`,
    `closedon_userid`,
    `default_savings_product`,
    `default_savings_account`,
    `client_type_cv_id`,
    `client_classification_cv_id`,
    `reject_reason_cv_id`,
    `rejectedon_date`,
    `rejectedon_userid`,
    `withdraw_reason_cv_id`,
    `withdrawn_on_date`,
    `withdraw_on_userid`,
    `reactivated_on_date`,
    `reactivated_on_userid`,
    `legal_form_enum`,
    `reopened_on_date`,
    `reopened_by_userid`,
    `email_address`,
    `proposed_transfer_date`,
    `created_on_utc`,
    `created_by`,
    `last_modified_by`,
    `last_modified_on_utc`,
    `etl_time`
)
SELECT
    src.`id`,
    CASE WHEN src.`account_no` IS NULL THEN NULL ELSE SHA2(CAST(src.`account_no` AS STRING), 256) END AS `account_no`,
    CASE WHEN src.`external_id` IS NULL THEN NULL ELSE SHA2(CAST(src.`external_id` AS STRING), 256) END AS `external_id`,
    src.`status_enum`,
    src.`sub_status`,
    src.`activation_date`,
    src.`office_joining_date`,
    src.`office_id`,
    src.`transfer_to_office_id`,
    src.`staff_id`,
    CASE WHEN src.`firstname` IS NULL THEN NULL ELSE '***' END AS `firstname`,
    CASE WHEN src.`middlename` IS NULL THEN NULL ELSE '***' END AS `middlename`,
    CASE WHEN src.`lastname` IS NULL THEN NULL ELSE '***' END AS `lastname`,
    CASE WHEN src.`fullname` IS NULL THEN NULL ELSE '***' END AS `fullname`,
    CASE WHEN src.`display_name` IS NULL THEN NULL ELSE '***' END AS `display_name`,
    CASE WHEN src.`mobile_no` IS NULL THEN NULL ELSE SHA2(CAST(src.`mobile_no` AS STRING), 256) END AS `mobile_no`,
    src.`is_staff`,
    src.`gender_cv_id`,
    CASE WHEN src.`date_of_birth` IS NULL THEN NULL ELSE '***' END AS `date_of_birth`,
    src.`image_id`,
    src.`closure_reason_cv_id`,
    src.`closedon_date`,
    src.`updated_by`,
    src.`updated_on`,
    src.`submittedon_date`,
    src.`activatedon_userid`,
    src.`closedon_userid`,
    src.`default_savings_product`,
    src.`default_savings_account`,
    src.`client_type_cv_id`,
    src.`client_classification_cv_id`,
    src.`reject_reason_cv_id`,
    src.`rejectedon_date`,
    src.`rejectedon_userid`,
    src.`withdraw_reason_cv_id`,
    src.`withdrawn_on_date`,
    src.`withdraw_on_userid`,
    src.`reactivated_on_date`,
    src.`reactivated_on_userid`,
    src.`legal_form_enum`,
    src.`reopened_on_date`,
    src.`reopened_by_userid`,
    CASE WHEN src.`email_address` IS NULL THEN NULL ELSE SHA2(CAST(src.`email_address` AS STRING), 256) END AS `email_address`,
    src.`proposed_transfer_date`,
    src.`created_on_utc`,
    src.`created_by`,
    src.`last_modified_by`,
    src.`last_modified_on_utc`,
    CURRENT_TIMESTAMP AS `etl_time`
FROM retail_banking_dm.ods_fineract_m_client AS src;
