SET @etl_date = COALESCE(@etl_date, CURDATE());

-- Human-reviewed semantic target: retail_banking_dm.dwd_loan_transaction
TRUNCATE TABLE retail_banking_dm.dwd_loan_transaction;

INSERT INTO retail_banking_dm.dwd_loan_transaction (
    `id`,
    `loan_id`,
    `office_id`,
    `payment_detail_id`,
    `is_reversed`,
    `external_id`,
    `transaction_type_enum`,
    `transaction_date`,
    `amount`,
    `principal_portion_derived`,
    `interest_portion_derived`,
    `fee_charges_portion_derived`,
    `penalty_charges_portion_derived`,
    `overpayment_portion_derived`,
    `unrecognized_income_portion`,
    `outstanding_loan_balance_derived`,
    `submitted_on_date`,
    `manually_adjusted_or_reversed`,
    `created_date`,
    `created_by`,
    `last_modified_by`,
    `created_on_utc`,
    `last_modified_on_utc`,
    `charge_refund_charge_type`,
    `reversal_external_id`,
    `reversed_on_date`,
    `version`,
    `classification_cv_id`,
    `business_date`,
    `etl_time`
)
SELECT
    src.`id`,
    src.`loan_id`,
    src.`office_id`,
    src.`payment_detail_id`,
    src.`is_reversed`,
    CASE WHEN src.`external_id` IS NULL THEN NULL ELSE SHA2(CAST(src.`external_id` AS STRING), 256) END AS `external_id`,
    src.`transaction_type_enum`,
    src.`transaction_date`,
    src.`amount`,
    src.`principal_portion_derived`,
    src.`interest_portion_derived`,
    src.`fee_charges_portion_derived`,
    src.`penalty_charges_portion_derived`,
    src.`overpayment_portion_derived`,
    src.`unrecognized_income_portion`,
    src.`outstanding_loan_balance_derived`,
    src.`submitted_on_date`,
    src.`manually_adjusted_or_reversed`,
    src.`created_date`,
    src.`created_by`,
    src.`last_modified_by`,
    src.`created_on_utc`,
    src.`last_modified_on_utc`,
    src.`charge_refund_charge_type`,
    CASE WHEN src.`reversal_external_id` IS NULL THEN NULL ELSE SHA2(CAST(src.`reversal_external_id` AS STRING), 256) END AS `reversal_external_id`,
    src.`reversed_on_date`,
    src.`version`,
    src.`classification_cv_id`,
    DATE(src.`transaction_date`) AS `business_date`,
    CURRENT_TIMESTAMP AS `etl_time`
FROM retail_banking_dm.ods_fineract_m_loan_transaction AS src;
