SET @etl_date = COALESCE(@etl_date, CURDATE());

-- Human-reviewed semantic target: retail_banking_dm.dwd_deposit_transaction
TRUNCATE TABLE retail_banking_dm.dwd_deposit_transaction;

INSERT INTO retail_banking_dm.dwd_deposit_transaction (
    `id`,
    `savings_account_id`,
    `office_id`,
    `payment_detail_id`,
    `transaction_type_enum`,
    `is_reversed`,
    `transaction_date`,
    `amount`,
    `overdraft_amount_derived`,
    `balance_end_date_derived`,
    `balance_number_of_days_derived`,
    `running_balance_derived`,
    `cumulative_balance_derived`,
    `created_date`,
    `created_by`,
    `is_manual`,
    `release_id_of_hold_amount`,
    `is_loan_disbursement`,
    `ref_no`,
    `original_transaction_id`,
    `is_reversal`,
    `reason_for_block`,
    `is_lien_transaction`,
    `submitted_on_date`,
    `last_modified_by`,
    `created_on_utc`,
    `last_modified_on_utc`,
    `external_id`,
    `business_date`,
    `etl_time`
)
SELECT
    src.`id`,
    src.`savings_account_id`,
    src.`office_id`,
    src.`payment_detail_id`,
    src.`transaction_type_enum`,
    src.`is_reversed`,
    src.`transaction_date`,
    src.`amount`,
    src.`overdraft_amount_derived`,
    src.`balance_end_date_derived`,
    src.`balance_number_of_days_derived`,
    src.`running_balance_derived`,
    src.`cumulative_balance_derived`,
    src.`created_date`,
    src.`created_by`,
    src.`is_manual`,
    src.`release_id_of_hold_amount`,
    src.`is_loan_disbursement`,
    src.`ref_no`,
    src.`original_transaction_id`,
    src.`is_reversal`,
    src.`reason_for_block`,
    src.`is_lien_transaction`,
    src.`submitted_on_date`,
    src.`last_modified_by`,
    src.`created_on_utc`,
    src.`last_modified_on_utc`,
    CASE WHEN src.`external_id` IS NULL THEN NULL ELSE SHA2(CAST(src.`external_id` AS STRING), 256) END AS `external_id`,
    DATE(src.`transaction_date`) AS `business_date`,
    CURRENT_TIMESTAMP AS `etl_time`
FROM retail_banking_dm.ods_fineract_m_savings_account_transaction AS src;
