SET @etl_date = CURDATE();

DELETE FROM retail_banking_dm.dwd_wc_loan_account_daily_snapshot
WHERE `snapshot_date` = CAST(@etl_date AS DATE);

INSERT INTO retail_banking_dm.dwd_wc_loan_account_daily_snapshot (
    `id`,
    `version`,
    `created_by`,
    `last_modified_by`,
    `created_on_utc`,
    `last_modified_on_utc`,
    `loan_status_id`,
    `last_closed_business_date`,
    `account_no`,
    `external_id`,
    `client_id`,
    `fund_id`,
    `product_id`,
    `submittedon_date`,
    `rejectedon_date`,
    `rejectedon_userid`,
    `approvedon_date`,
    `approvedon_userid`,
    `closedon_date`,
    `closedon_userid`,
    `expected_maturedon_date`,
    `maturedon_date`,
    `principal_amount_proposed`,
    `approved_principal`,
    `currency_code`,
    `currency_digits`,
    `currency_multiplesof`,
    `principal_amount`,
    `period_payment_rate`,
    `repayment_every`,
    `repayment_frequency_enum`,
    `amortization_type`,
    `npv_day_count`,
    `discount`,
    `delinquency_bucket_classification_id`,
    `loan_counter`,
    `loan_product_counter`,
    `delinquency_grace_days`,
    `delinquency_start_type`,
    `wc_loan_product_id`,
    `breach_id`,
    `near_breach_id`,
    `discount_proposed`,
    `discount_approved`,
    `total_payment_volume`,
    `breach_grace_days`,
    `snapshot_date`,
    `etl_time`
)
SELECT
    src.`id`,
    src.`version`,
    src.`created_by`,
    src.`last_modified_by`,
    src.`created_on_utc`,
    src.`last_modified_on_utc`,
    src.`loan_status_id`,
    src.`last_closed_business_date`,
    CASE WHEN src.`account_no` IS NULL THEN NULL ELSE SHA2(CAST(src.`account_no` AS STRING), 256) END AS `account_no`,
    CASE WHEN src.`external_id` IS NULL THEN NULL ELSE SHA2(CAST(src.`external_id` AS STRING), 256) END AS `external_id`,
    src.`client_id`,
    src.`fund_id`,
    src.`product_id`,
    src.`submittedon_date`,
    src.`rejectedon_date`,
    src.`rejectedon_userid`,
    src.`approvedon_date`,
    src.`approvedon_userid`,
    src.`closedon_date`,
    src.`closedon_userid`,
    src.`expected_maturedon_date`,
    src.`maturedon_date`,
    src.`principal_amount_proposed`,
    src.`approved_principal`,
    src.`currency_code`,
    src.`currency_digits`,
    src.`currency_multiplesof`,
    src.`principal_amount`,
    src.`period_payment_rate`,
    src.`repayment_every`,
    src.`repayment_frequency_enum`,
    src.`amortization_type`,
    src.`npv_day_count`,
    src.`discount`,
    src.`delinquency_bucket_classification_id`,
    src.`loan_counter`,
    src.`loan_product_counter`,
    src.`delinquency_grace_days`,
    src.`delinquency_start_type`,
    src.`wc_loan_product_id`,
    src.`breach_id`,
    src.`near_breach_id`,
    src.`discount_proposed`,
    src.`discount_approved`,
    src.`total_payment_volume`,
    src.`breach_grace_days`,
    CAST(@etl_date AS DATE) AS `snapshot_date`,
    CURRENT_TIMESTAMP AS `etl_time`
FROM retail_banking_dm.ods_fineract_m_wc_loan AS src;
