SET @etl_date = CURDATE();

DELETE FROM retail_banking_dm.dwd_share_account_daily_snapshot
WHERE `snapshot_date` = CAST(@etl_date AS DATE);

INSERT INTO retail_banking_dm.dwd_share_account_daily_snapshot (
    `id`,
    `account_no`,
    `product_id`,
    `client_id`,
    `external_id`,
    `status_enum`,
    `total_approved_shares`,
    `total_pending_shares`,
    `submitted_date`,
    `submitted_userid`,
    `approved_date`,
    `approved_userid`,
    `rejected_date`,
    `rejected_userid`,
    `activated_date`,
    `activated_userid`,
    `closed_date`,
    `closed_userid`,
    `currency_code`,
    `currency_digits`,
    `currency_multiplesof`,
    `savings_account_id`,
    `minimum_active_period_frequency`,
    `minimum_active_period_frequency_enum`,
    `lockin_period_frequency`,
    `lockin_period_frequency_enum`,
    `allow_dividends_inactive_clients`,
    `created_date`,
    `lastmodifiedby_id`,
    `lastmodified_date`,
    `snapshot_date`,
    `etl_time`
)
SELECT
    src.`id`,
    CASE WHEN src.`account_no` IS NULL THEN NULL ELSE SHA2(CAST(src.`account_no` AS STRING), 256) END AS `account_no`,
    src.`product_id`,
    src.`client_id`,
    CASE WHEN src.`external_id` IS NULL THEN NULL ELSE SHA2(CAST(src.`external_id` AS STRING), 256) END AS `external_id`,
    src.`status_enum`,
    src.`total_approved_shares`,
    src.`total_pending_shares`,
    src.`submitted_date`,
    src.`submitted_userid`,
    src.`approved_date`,
    src.`approved_userid`,
    src.`rejected_date`,
    src.`rejected_userid`,
    src.`activated_date`,
    src.`activated_userid`,
    src.`closed_date`,
    src.`closed_userid`,
    src.`currency_code`,
    src.`currency_digits`,
    src.`currency_multiplesof`,
    src.`savings_account_id`,
    src.`minimum_active_period_frequency`,
    src.`minimum_active_period_frequency_enum`,
    src.`lockin_period_frequency`,
    src.`lockin_period_frequency_enum`,
    src.`allow_dividends_inactive_clients`,
    src.`created_date`,
    src.`lastmodifiedby_id`,
    src.`lastmodified_date`,
    CAST(@etl_date AS DATE) AS `snapshot_date`,
    CURRENT_TIMESTAMP AS `etl_time`
FROM retail_banking_dm.ods_fineract_m_share_account AS src;
