SET @etl_date = COALESCE(@etl_date, CURDATE());

-- Human-reviewed semantic target: retail_banking_dm.dwd_loan_installment
DELETE FROM retail_banking_dm.dwd_loan_installment
WHERE `business_date` = CAST(@etl_date AS DATE);
DELETE FROM retail_banking_dm.dwd_loan_installment
WHERE `business_date` IS NULL;

INSERT INTO retail_banking_dm.dwd_loan_installment (
    `id`,
    `loan_id`,
    `fromdate`,
    `duedate`,
    `installment`,
    `principal_amount`,
    `principal_completed_derived`,
    `principal_writtenoff_derived`,
    `interest_amount`,
    `interest_completed_derived`,
    `interest_writtenoff_derived`,
    `interest_waived_derived`,
    `accrual_interest_derived`,
    `reschedule_interest_portion`,
    `fee_charges_amount`,
    `fee_charges_completed_derived`,
    `fee_charges_writtenoff_derived`,
    `fee_charges_waived_derived`,
    `accrual_fee_charges_derived`,
    `penalty_charges_amount`,
    `penalty_charges_completed_derived`,
    `penalty_charges_writtenoff_derived`,
    `penalty_charges_waived_derived`,
    `accrual_penalty_charges_derived`,
    `total_paid_in_advance_derived`,
    `total_paid_late_derived`,
    `completed_derived`,
    `obligations_met_on_date`,
    `created_by`,
    `created_date`,
    `lastmodified_date`,
    `last_modified_by`,
    `recalculated_interest_component`,
    `created_on_utc`,
    `last_modified_on_utc`,
    `is_additional`,
    `credits_amount`,
    `is_down_payment`,
    `credited_interest`,
    `credited_fee`,
    `credited_penalty`,
    `is_re_aged`,
    `business_date`,
    `etl_time`
)
SELECT
    src.`id`,
    src.`loan_id`,
    src.`fromdate`,
    src.`duedate`,
    src.`installment`,
    src.`principal_amount`,
    src.`principal_completed_derived`,
    src.`principal_writtenoff_derived`,
    src.`interest_amount`,
    src.`interest_completed_derived`,
    src.`interest_writtenoff_derived`,
    src.`interest_waived_derived`,
    src.`accrual_interest_derived`,
    src.`reschedule_interest_portion`,
    src.`fee_charges_amount`,
    src.`fee_charges_completed_derived`,
    src.`fee_charges_writtenoff_derived`,
    src.`fee_charges_waived_derived`,
    src.`accrual_fee_charges_derived`,
    src.`penalty_charges_amount`,
    src.`penalty_charges_completed_derived`,
    src.`penalty_charges_writtenoff_derived`,
    src.`penalty_charges_waived_derived`,
    src.`accrual_penalty_charges_derived`,
    src.`total_paid_in_advance_derived`,
    src.`total_paid_late_derived`,
    src.`completed_derived`,
    src.`obligations_met_on_date`,
    src.`created_by`,
    src.`created_date`,
    src.`lastmodified_date`,
    src.`last_modified_by`,
    src.`recalculated_interest_component`,
    src.`created_on_utc`,
    src.`last_modified_on_utc`,
    src.`is_additional`,
    src.`credits_amount`,
    src.`is_down_payment`,
    src.`credited_interest`,
    src.`credited_fee`,
    src.`credited_penalty`,
    src.`is_re_aged`,
    DATE(src.`duedate`) AS `business_date`,
    CURRENT_TIMESTAMP AS `etl_time`
FROM retail_banking_dm.ods_fineract_m_loan_repayment_schedule AS src
WHERE DATE(src.`duedate`) = CAST(@etl_date AS DATE)
   OR DATE(src.`duedate`) IS NULL;
