"""
Configuration package for data warehouse projects.
"""

from . import core
from .assets import (
    assess_cache_path,
    assess_result_path,
    asset_role_for_layer,
    clear_model_metadata_cache,
    determine_layer,
    get_model_layer,
    get_model_metadata,
    get_model_names_by_layer,
    iter_project_asset_files,
    iter_project_task_files,
    job_dag_path,
    layer_rank,
    lineage_data_path,
    lineage_html_path,
    lineage_job_html_path,
    lineage_task_cache_path,
    load_model_metadata,
    model_metadata_result_path,
    model_path_for_table,
    ods_source_catalog_ddl_dialect,
    project_artifact_dir,
    project_asset_dirs,
    project_dir,
    project_ods_asset_dir,
    project_ods_asset_dirs,
    project_ods_source_catalog_dialects,
    project_task_dirs,
    task_path_for_job,
    task_path_for_source_file,
    task_source_file,
)
from .naming import (
    LayerDef,
    NamingConfig,
    TypeDef,
    clear_naming_config_cache,
    get_naming_config,
    load_naming_config,
    naming_config_path,
)
from .semantics import (
    BUSINESS_PROCESSES_FILE_NAME,
    BUSINESS_SEMANTICS_FILE_NAMES,
    BUSINESS_TAXONOMY_FILE_NAME,
    SEMANTIC_SUBJECTS_FILE_NAME,
    BusinessAreaDef,
    BusinessDomainConfig,
    DomainDef,
    business_processes_path,
    business_semantics_dir,
    business_semantics_paths,
    business_taxonomy_path,
    clear_business_semantics_cache,
    get_business_domain_config,
    load_business_semantics_catalog,
    load_business_semantics_catalog_from_dir,
    semantic_subjects_path,
)

_CORE_EXPORTS = {
    "DB_ENV_CONFIG",
    "DORIS_HOST",
    "DORIS_HTTP_PORT",
    "DORIS_PORT",
    "DORIS_QA_USER",
    "DORIS_USER",
    "LAYER_ORDER",
    "PROJECT_CONFIG",
    "PROJECT_MAP",
    "PROJECT_ROOT",
    "TEXT_ENCODING",
    "get_mysql_cmd",
}

__all__ = [
    "BUSINESS_PROCESSES_FILE_NAME",
    "BUSINESS_SEMANTICS_FILE_NAMES",
    "BUSINESS_TAXONOMY_FILE_NAME",
    "SEMANTIC_SUBJECTS_FILE_NAME",
    "BusinessAreaDef",
    "BusinessDomainConfig",
    "DB_ENV_CONFIG",
    "DORIS_HOST",
    "DORIS_HTTP_PORT",
    "DORIS_PORT",
    "DORIS_QA_USER",
    "DORIS_USER",
    "DomainDef",
    "LAYER_ORDER",
    "LayerDef",
    "NamingConfig",
    "PROJECT_CONFIG",
    "PROJECT_MAP",
    "PROJECT_ROOT",
    "TEXT_ENCODING",
    "TypeDef",
    "assess_cache_path",
    "assess_result_path",
    "asset_role_for_layer",
    "business_processes_path",
    "business_semantics_dir",
    "business_semantics_paths",
    "business_taxonomy_path",
    "clear_business_semantics_cache",
    "clear_model_metadata_cache",
    "clear_naming_config_cache",
    "determine_layer",
    "get_business_domain_config",
    "get_model_layer",
    "get_model_metadata",
    "get_model_names_by_layer",
    "get_mysql_cmd",
    "get_naming_config",
    "iter_project_asset_files",
    "iter_project_task_files",
    "job_dag_path",
    "layer_rank",
    "lineage_data_path",
    "lineage_html_path",
    "lineage_job_html_path",
    "lineage_task_cache_path",
    "load_business_semantics_catalog",
    "load_business_semantics_catalog_from_dir",
    "load_model_metadata",
    "load_naming_config",
    "model_metadata_result_path",
    "model_path_for_table",
    "naming_config_path",
    "ods_source_catalog_ddl_dialect",
    "project_artifact_dir",
    "project_asset_dirs",
    "project_dir",
    "project_ods_asset_dir",
    "project_ods_asset_dirs",
    "project_ods_source_catalog_dialects",
    "project_task_dirs",
    "semantic_subjects_path",
    "task_path_for_job",
    "task_path_for_source_file",
    "task_source_file",
]


def __getattr__(name: str):
    if name in _CORE_EXPORTS:
        return getattr(core, name)
    raise AttributeError(f"module 'config' has no attribute {name!r}")
